### ISSUE TITLE
feat(Exercise): get vote from the connected user when accessing one exercise

### ISSUE THREAD

**Issue by dewita** [SourceCodeOER/sourcecode_api#28]

**Comment by jy95** [comment]
The only solution ( if not a new endpoint ) is to **tweak current structure to do that**

What are the problems : 
- The endpoint [/api/exercises/{id}](https://sourcecodeoer.github.io/sourcecode_api/#operation/getExerciseByID) OAS : 
 It doesn't need a security check from now so to detect the user, you use add the authorization header when you want the user vote but keep the endpoint accessible to guest too : security must be optional

```yaml
security:
  - {}
  - bearerAuth: []
```

( [Stackoverflow source](https://stackoverflow.com/a/48196118/6149867) and [Link to explanation](https://github.com/OAI/OpenAPI-Specification/issues/14#issuecomment-297457320) )

( TODO : check how `openapi-enforcer` will handle this case )

- The [middlewares/security.js](https://github.com/SourceCodeOER/sourcecode_api/blob/master/middlewares/security.js#L71) file : 

How it is highly likely that other endpoints will undergo the same logic of optionality, the cleanest way to deal with this kind of case is to introduce some code to detect that

I'm going to see how I'm going to deal with these problems today ...
