### ISSUE TITLE
feat(api): order by id

### ISSUE THREAD

**Issue by dewita** [SourceCodeOER/sourcecode_api#40]
Add this feature for configurations, exercises, tags, categories

**Comment by jy95** [comment]
Afart the sorting of tags ( that will be done later ), everything else is ready : 

What was done ?
- [configurations](https://github.com/SourceCodeOER/sourcecode_api/blob/master/controllers/configurations/fetchOwnConfigurations.js) now sorts by default the configurations by id ( Ascending sort )
- [tags categories](https://github.com/SourceCodeOER/sourcecode_api/blob/advancedFiltering/controllers/tags_categories/getTagCategoriesWithTags.js) now sorts by default tag categories by id ( Ascending sort )
- [exercises](https://github.com/SourceCodeOER/sourcecode_api/blob/master/models/exercise.js#L53) now have a custom way to deal order clauses. See documentation of [endpoint](https://sourcecodeoer.github.io/sourcecode_api/#operation/searchExercises) for more information
