### ISSUE TITLE
feat(api): /api/search - add rating filtering

### ISSUE THREAD

**Issue by dewita** [SourceCodeOER/sourcecode_api#41]

**Comment by jy95** [comment]
Feature implemented in branch **advancedFiltering**

**Comment by dewita** [comment]
Missing the following cases :

- Give me all the exercises with more than 3 stars
- Give me all the exercises with less than 2 stars

**Comment by jy95** [comment]
I think you are wrong : 
Using the following `data ->vote` should fix your problems : 

{"operator" : ">", "value": 3.0}
{"operator" : "<", "value": 2.0}
